name: msu_hockey
description: A Dart implementation of the MSU Hockey webpage
version: 0.0.1
#homepage: https://www.example.com
#author: Dan <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  over_react: ^1.24.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- over_react
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
